AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A starter AWS Lambda function.

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-python3.9/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
